"""Lightweight command names, shared without importing the image renderer."""

EFFECTS = (
    "brightness",
    "contrast",
    "saturation",
    "hue",
    "exposure",
    "gamma",
    "temperature",
    "tint",
    "shadows",
    "highlights",
    "levels",
    "curves",
    "blur",
    "gaussian-blur",
    "sharpen",
    "grayscale",
    "invert",
    "posterize",
    "threshold",
    "noise",
    "grain",
    "vignette",
    "auto-tone",
    "auto-color",
    "auto-contrast",
)
